'use client';
import {useEffect,useRef,useState, type ReactNode} from 'react';
import {Layers3,Workflow,GitBranch,Braces,ArrowUpRight,ArrowRight,Plus,Minus,Maximize2,BookOpen,Network,ChevronRight,Database,Download} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import source from '@/lib/docs-data.json';

type View='detailed'|'face'|'technical'|'data'|'tests'|'components'|'modules'|'usecases'|'flows'|'api';
type Node={id:string;text:string;x:number;y:number;w:number;h:number;style:Record<string,string>;parent:string;lane:string;apis:string[]};
type Edge={id:string;source:string;target:string;text:string;style:Record<string,string>;points:{x:number;y:number}[]};
type Diagram={id:string;name:string;width:number;height:number;nodes:Node[];edges:Edge[]};
type Api={id:string;module:string;title:string;method:string;path:string;caller:string;input:string;output:string;rules:string;flowNote:string;refs:string};
const data=source as unknown as {detailedDesign:string;faceResearch:string;technicalArchitecture:string;runtimeNotes:string;dataArchitecture:string;tableCount:number;checklist:string;decisions:string;scenarioCount:number;components:Diagram[];modules:Diagram[];usecases:Diagram[];flows:Diagram[];apis:Api[];sections:{title:string;markdown:string}[];moduleCards:{id:string;name:string;parts:string[];apis:string[]}[]};
const navigation=[{id:'detailed' as View,name:'详细设计',icon:BookOpen,count:'15'},{id:'face' as View,name:'人脸服务调研',icon:BookOpen,count:'MVP'},{id:'technical' as View,name:'技术架构',icon:Workflow,count:'Java/Py'},{id:'data' as View,name:'数据架构',icon:Database,count:String(data.tableCount)},{id:'tests' as View,name:'测试清单',icon:BookOpen,count:String(data.scenarioCount)},{id:'components' as View,name:'运行组件图',icon:Workflow,count:'05'},{id:'modules' as View,name:'五模块图',icon:Layers3,count:'05'},{id:'usecases' as View,name:'用例图',icon:Network,count:'03'},{id:'flows' as View,name:'流程图',icon:GitBranch,count:'08'},{id:'api' as View,name:'API 列表',icon:Braces,count:'27'}];
const flowDescriptions=['从云台测肤到两端护理，串联完整业务。','云台认证、心跳、配网登录绑定与异常通知。','三视角照片、补拍、成员归档和报告生成。','同一报告与方案，面向 APP 和云台分别展示。','先核验再执行，追丢后的暂停、重验与恢复。','永久查看授权、主动撤销和非 MVP 测肤边界。','实际次数上传、去重累计与完成判定。','APP 本地控制微晶，换人重验与执行收尾。'];
const documentLinks:Record<string,string>={'后端详细设计-V1-MVP.md':'#detailed','references/face-insightface-code-review.md':'/downloads/references/face-insightface-code-review.md','人脸服务调研与推荐方案-V1-MVP.md':'#face','数据架构设计-V1-五模块-MVP.md':'#data','技术架构设计-V1-MVP.md':'#technical','assets/runtime-components.mmd':'/downloads/assets/runtime-components.mmd','后端API接口设计-V1-五模块与流程对应.md':'#api','测试需求决策记录.md':'#tests','测试场景清单-V1-五模块与双控制.md':'#tests','运行组件说明.md':'#components'};
function Inline({text}:{text:string}){return <>{text.split(/(\[[^\]]+\]\([^)]+\)|M[1-5]-A\d{2}|`[^`]+`|\*\*[^*]+\*\*)/g).map((s,i)=>{const link=s.match(/^\[([^\]]+)\]\(([^)]+)\)$/);if(link){const href=documentLinks[link[2]]??(/^https:\/\//.test(link[2])?link[2]:undefined);return href?<a className="doc-link" href={href} key={i}>{link[1]}</a>:<span key={i}>{link[1]}</span>}return /^M[1-5]-A\d{2}$/.test(s)?<a className="api-link" href={'#api/'+s} key={i}>{s}</a>:s.startsWith('`')?<code key={i}>{s.slice(1,-1)}</code>:s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s})}</>}
function DomainRelations({text}:{text:string}){const names:Record<string,string>={ACCOUNT:'账号 accounts',MEMBER:'成员 members',MEMBER_ACCESS_GRANT:'成员授权 member_access_grants',GIMBAL:'云台 gimbals',MICROCRYSTAL:'微晶 microcrystals',SKIN_ASSESSMENT:'测肤任务 skin_assessments',CARE_PLAN:'护理方案 care_plans',CARE_EXECUTION:'护理执行 care_executions',CARE_RECORD:'次数明细 care_records',NOTIFICATION_DESTINATION:'推送目标 notification_destinations',NOTIFICATION:'通知 notifications'};const cardinality:Record<string,string>={'||':'1','o|':'0 或 1','|o':'0 或 1','o{':'0 到多','}o':'0 到多','|{':'1 到多','}|':'1 到多'};const rows=text.split('\n').flatMap(line=>{const m=line.trim().match(/^(\w+)\s+([|o{}]+)--([|o{}]+)\s+(\w+)\s*:\s*"([^"]+)"$/);return m?[m]:[]});return <div className="domain-relations"><h3>领域关系 · 逐项阅读</h3><Table className="prose-table"><TableHeader><TableRow>{['对象','数量关系','关联对象','业务含义'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}><TableCell>{names[r[1]]??r[1]}</TableCell><TableCell>{cardinality[r[2]]??r[2]} → {cardinality[r[3]]??r[3]}</TableCell><TableCell>{names[r[4]]??r[4]}</TableCell><TableCell>{r[5]}</TableCell></TableRow>)}</TableBody></Table></div>}
function Markdown({text}:{text:string}){
 const lines=text.split('\n');const out:ReactNode[]=[];
 for(let i=0;i<lines.length;i++){const l=lines[i];if(!l.trim())continue;
 const diagramImage=l.match(/^!\[([^\]]*)\]\(assets\/runtime-components\.svg\)$/);if(diagramImage){out.push(<figure className="architecture-figure" key={i}><a href="/downloads/assets/runtime-components.svg" target="_blank" rel="noreferrer" aria-label="打开完整通信图"><img src="/downloads/assets/runtime-components.svg" alt={diagramImage[1]} width={1570} height={965}/></a><figcaption>固定布局通信图 · 点击可打开原图放大查看</figcaption></figure>);continue;}
 if(l.startsWith('```')){const lang=l.slice(3).trim();const block:string[]=[];i++;while(i<lines.length&&!lines[i].startsWith('```')){block.push(lines[i]);i++}const body=block.join('\n');out.push(lang==='mermaid'&&body.trim().startsWith('flowchart')?<div className="domain-relations" key={i}><h3>自建人脸服务 · 通信关系</h3><p>Java Web → Python 人脸服务：搜索、指定成员核验</p><p>Python 异步 Worker → Python 人脸服务：搜索、新人登记</p><p>Python 人脸服务 → PostgreSQL：人员、特征与状态</p><p>Python 人脸服务 → 私有 OSS：图片存储与受控读取</p></div>:lang==='mermaid'&&body.trim().startsWith('erDiagram')?<DomainRelations text={body} key={i}/>:<pre className="doc-code" key={i}><code>{body}</code></pre>);continue;}

 if(l.startsWith('|')){const rows:string[][]=[];while(i<lines.length&&lines[i].startsWith('|')){if(!/^\|[\s:|\-]+\|$/.test(lines[i]))rows.push(lines[i].split('|').slice(1,-1).map(c=>c.trim()));i++}i--;out.push(<Table key={i} className="prose-table"><TableHeader><TableRow>{rows[0]?.map((c,j)=><TableHead key={j}><Inline text={c}/></TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(1).map((row,j)=><TableRow key={j}>{row.map((c,k)=><TableCell key={k}><Inline text={c}/></TableCell>)}</TableRow>)}</TableBody></Table>);continue;}
 if(/^#{1,4} /.test(l)){out.push(<h3 key={i}>{l.replace(/^#{1,4} /,'')}</h3>);continue}
 if(/^(\d+\. |- )/.test(l)){out.push(<p className="prose-list" key={i}><span className="list-marker">{/^\d/.test(l)?l.match(/^\d+/)?.[0]: '•'}</span><span><Inline text={l.replace(/^(\d+\. |- )/,'')}/></span></p>);continue}
 out.push(<p key={i}><Inline text={l}/></p>)}return <div className="prose-doc">{out}</div>
}
function ArchitectureDocument({kind,selected}:{kind:'data'|'technical'|'face'|'detailed';selected?:string}){
 const documents={
  detailed:{text:data.detailedDesign,title:'后端详细设计',eyebrow:'DETAILED DESIGN / MVP',intro:'27 个业务接口 · 状态机、事务、计数与收尾、异步任务及故障恢复。',status:'开发设计草案 · 尚未实现业务系统',download:'detailed-design.md'},
  face:{text:data.faceResearch,title:'人脸服务调研与推荐方案',eyebrow:'FACE SERVICES / MVP',intro:'云服务能力对照 · 阿里云接入建议 · 自建人脸服务 MVP 改造与验收。',status:'调研与工程建议 · 尚未完成设备验证',download:'face-research.md'},
  technical:{text:data.technicalArchitecture,title:'技术架构设计',eyebrow:'TECHNICAL ARCHITECTURE / MVP',intro:'Java Web 后端 + Python 异步 Worker · 工程组织、任务交接、事务与部署。',status:'设计初稿 · 尚未部署业务系统',download:'technical-architecture.md'},
  data:{text:data.dataArchitecture,title:'数据架构设计',eyebrow:'DATA ARCHITECTURE / MVP',intro:`五模块领域模型 · ${data.tableCount} 张表（含账号表）· 默认不写 JOIN 的接口查询路径。`,status:'设计初稿 · 尚未建表',download:'data-architecture.md'}
 };const doc=documents[kind];const sections=Array.from(doc.text.matchAll(/^## ([^\n]+)\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm),m=>({title:m[1],body:m[2].trim(),id:m[1].match(/^\d+/)?.[0]??m[1]}));
 useEffect(()=>{if(selected)document.getElementById(kind+'-section-'+selected)?.scrollIntoView({block:'start'})},[kind,selected]);
 return <><div className="eyebrow">{doc.eyebrow}</div><h1>{doc.title}</h1><p className="intro">{doc.intro}</p><div className="architecture-actions"><span className="design-draft">{doc.status}</span><a className="doc-download" href={'/downloads/'+doc.download} download><Download size={17}/>下载 Markdown</a></div><nav className="architecture-toc" aria-label={doc.title+'章节'}>{sections.map(section=><a key={section.id} href={'#'+kind+'/'+section.id}>{section.title}</a>)}</nav>{sections.map(section=><section className="architecture-section" id={kind+'-section-'+section.id} key={section.id}><h2>{section.title}</h2><Markdown text={section.body}/></section>)}</>
}
function SideNavigation({view,onNavigate}:{view:View;onNavigate:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader><a href="#modules" className="brand"><span className="brand-symbol">L</span><span>LANSEE<small>后端设计文档</small></span></a></SidebarHeader><SidebarContent><div className="nav-label">文档目录</div><SidebarMenu>{navigation.map(({id,name,icon:Icon,count})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>{onNavigate(id);setOpenMobile(false)}}><Icon size={18}/><span>{name}</span><span className="nav-count">{count}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><span className="tiny-label">当前范围</span><p>APP 与云台双控制<br/>一种微晶 · 一个方案版本</p><div className="sidebar-rule"><span>N / K</span>统一按次数计量</div></div></SidebarContent><SidebarFooter><div className="sidebar-bottom"><span className="green-dot"/>已对齐模块、用例与 API<small>27 个对外 HTTP 接口</small></div></SidebarFooter></Sidebar>}
function ConfirmedRules(){return <div className="boundary-row"><div><h2>云台只保留当前任务</h2><p>后端持久保存唯一当前任务及 N/K。重启用 <Inline text="M3-A06"/> 恢复；当前方案未完成可跨次继续，每次开始/恢复仍核验人脸。云台不能查询历史报告或历史方案。</p></div><div><h2>新测肤如何替换</h2><p>用户先结束云台当前护理，实际停止、记录同步并收尾后才能新测肤。新任务受理即替换当前关联，补拍/分析失败不回退；旧资料和进度仍供已授权 APP 查询和继续使用。</p></div></div>}
function TestChecklist(){return <><div className="eyebrow">TEST SCENARIOS</div><h1>测试场景清单</h1><p className="intro">{data.scenarioCount} 个场景 · 覆盖 27 个 API · 尚未执行测试。业务决策已确认，剩余技术条件由开发对接。</p><ConfirmedRules/><Tabs defaultValue="checklist"><TabsList><TabsTrigger value="checklist">场景与开发对接项</TabsTrigger><TabsTrigger value="decisions">已确认决策</TabsTrigger></TabsList><TabsContent value="checklist"><Markdown text={data.checklist}/></TabsContent><TabsContent value="decisions"><Markdown text={data.decisions}/></TabsContent></Tabs></>}
function ComponentOverview(){return <><div className="eyebrow">RUNTIME / 00</div><h1>五个运行组件，图片统一保存到 OSS。</h1><p className="intro">Nginx、Java Web 后端、PostgreSQL、Python 异步 Worker 与 OSS 对象存储。图中同时展示 APP、云台、微晶、算法、大模型及通知通道。</p><div className="rulebar"><b>建议保留异步程序</b><span>测肤分析、方案生成、离线监测与通知重试，需要在请求结束后继续执行。</span></div><DiagramCollection kind="components"/><p className="intro"><a className="doc-link" href="#technical/3">查看固定布局通信图和 Java / Python 技术架构</a></p><ConfirmedRules/><div className="boundary-row"><div><h2>五模块与五组件是什么关系？</h2><p>M1—M5 划分代码职责；五个组件划分运行程序、数据库和对象存储。Java Web 与 Python Worker 分别构建镜像，通过 PG 工作项交接，四个自建组件可部署在同一台服务器，OSS 使用独立托管存储。</p></div><div><h2>初版不增加消息队列</h2><p>Web 将任务与业务状态一起存入 PG；异步程序领取任务并回写结果，处理超时与重试。暂不增加 Redis 或独立消息队列。</p></div></div><div className="boundary-row"><div><h2>账号绑定与异常通知</h2><p>APP 协助联网后，已登录先用 <Inline text="M2-A07"/> 查绑定状态，未绑定显示按钮，用户点击 <Inline text="M2-A06"/> 才绑定。原账号通过 <Inline text="M2-A08"/> 先解绑，新账号才可绑定。B 可以协助已绑定 A 的云台联网。M5-A01 登记通知目标；解绑不撤销成员授权或删除历史资料。</p></div><div><h2>数据与端侧控制</h2><p>OSS 保存云台、APP 拍照上传的图片和测肤结果图片；PG 保存业务数据、对象引用与归属。Web 接收上传照片并写入 OSS，异步程序读取原图、归档结果图；读取图片仍检查成员授权或云台当前任务。APP / 云台直接控制微晶，后端接收实际次数；执行前的人脸核验由 Web 调用算法服务。</p></div></div><p className="intro">通知通道、OSS 上传、受控读取与存储期限、配网凭据与接口细节由开发对接。绑定云台不授予成员资料查看权。</p></>}
function ModuleOverview(){return <><div className="eyebrow">ARCHITECTURE / 01</div><h1>五个模块，一套护理业务。</h1><p className="intro">身份与微晶连接测肤和护理，APP 与云台共享方案、记录和完成进度。</p><div className="statline"><span><b>5</b> 业务模块</span><span><b>27</b> HTTP API</span><span><b>8</b> 业务流程</span></div><div className="module-grid">{data.moduleCards.map(mod=><article className={'module-card '+(mod.id==='M4'?'care':'')} key={mod.id}><div className="card-top"><span className="module-code">{mod.id}</span><span>{mod.apis.length} 个接口</span></div><h2>{mod.name}</h2><div className={'module-parts '+(mod.id==='M4'?'care-parts':'')}>{mod.parts.map((text,i)=><div key={i}><h3>{text.split('\n')[0].replace(/〔原 M\d〕/,'')}</h3><p>{text.split('\n').slice(1).filter(Boolean).join('；')}</p></div>)}</div><a href={'#api/'+mod.apis[0]} className="card-foot"><span>查看 {mod.id} 接口</span><ArrowUpRight size={17}/></a></article>)}</div><div className="rulebar"><b>K ≥ N</b><span>达到目标次数即完成。剩余次数 = max(N − K, 0)。</span><span className="rule-source">以客户端上报次数为准</span></div><div className="boundary-row"><div><span className="tiny-label">控制边界</span><p>APP / 云台直接控制微晶。后端负责核验、登记与记录，不转发开始、暂停或停止指令。</p></div><div><span className="tiny-label">查看权限</span><p>人脸查看关联永久有效，直到账号主动撤销。查看授权不能代替本次执行核验。</p></div></div><Accordion className="source-accordion"><AccordionItem value="module-detail"><AccordionTrigger>完整模块图与流程对应 <span className="secondary">2 张图</span></AccordionTrigger><AccordionContent><DiagramCollection kind="modules" initial="01"/></AccordionContent></AccordionItem></Accordion></>}
function edgePath(edge:Edge,map:Map<string,Node>,straight=false){const s=map.get(edge.source),t=map.get(edge.target);if(!s||!t)return null;const sc={x:s.x+s.w/2,y:s.y+s.h/2},tc={x:t.x+t.w/2,y:t.y+t.h/2};
 function anchor(n:Node,to:{x:number;y:number},key:'exit'|'entry'){const sx=edge.style[key+'X'],sy=edge.style[key+'Y'];if(sx!==undefined&&sy!==undefined)return{x:n.x+Number(sx)*n.w,y:n.y+Number(sy)*n.h};const cx=n.x+n.w/2,cy=n.y+n.h/2,dx=to.x-cx,dy=to.y-cy;const k=Math.max(Math.abs(dx)/(n.w/2||1),Math.abs(dy)/(n.h/2||1))||1;return{x:cx+dx/k,y:cy+dy/k}}
 const waypoints=straight?[]:edge.points;const a=anchor(s,waypoints[0]??tc,'exit'),b=anchor(t,waypoints.at(-1)??sc,'entry');let pts=[a,...waypoints,b];if(!straight&&!edge.points.length&&Math.abs(a.x-b.x)>2&&Math.abs(a.y-b.y)>2){const mid=(a.y+b.y)/2;pts=[a,{x:a.x,y:mid},{x:b.x,y:mid},b]}
 const lengths=pts.slice(1).map((p,i)=>Math.hypot(p.x-pts[i].x,p.y-pts[i].y));let half=lengths.reduce((x,y)=>x+y,0)/2;let label=a;for(let i=0;i<lengths.length;i++){if(half<=lengths[i]){const q=half/(lengths[i]||1);label={x:pts[i].x+(pts[i+1].x-pts[i].x)*q,y:pts[i].y+(pts[i+1].y-pts[i].y)*q};break}half-=lengths[i]}return{points:pts.map(p=>p.x+','+p.y).join(' '),label}}
function DiagramCanvas({diagram,straight=false,readable=false}:{diagram:Diagram;straight?:boolean;readable?:boolean}){const [zoom,setZoom]=useState(.65);const wrap=useRef<HTMLDivElement>(null);const fit=()=>{if(wrap.current)setZoom(Math.min(1,Math.max(.3,(wrap.current.clientWidth-24)/diagram.width)))};useEffect(()=>{if(readable){setZoom(.75)}else{fit()}},[diagram.id,readable]);const map=new Map(diagram.nodes.map(n=>[n.id,n]));const parents=new Set(diagram.nodes.map(n=>n.parent));const backgrounds=diagram.nodes.filter(n=>parents.has(n.id));const foreground=diagram.nodes.filter(n=>!parents.has(n.id));const marker='arrow-'+diagram.id;
 function shape(n:Node){const st=n.style;const lane=st.swimlane==='1'||n.id.startsWith('lane');const textOnly=st.text==='1'||(st.strokeColor==='none'&&st.fillColor==='none');const actor=st.shape==='umlActor'||st.shape==='actor'||st.umlActor==='1';const diamond=st.rhombus==='1';const ellipse=st.ellipse==='1'||st.shape==='ellipse';const isContainer=parents.has(n.id);const fill=st.fillColor==='none'?'none':isContainer?'#f6f8fc':diamond?'#fff7e5':'#ffffff';const stroke=st.strokeColor==='none'?'none':diamond?'#cfb476':'#a9bbd1';const font=Number(st.fontSize||17);const displayFont=Math.min(font,readable?36:26);const actorLabelWidth=280;const actorLabelLines=n.text.split('\n').reduce((total,line)=>total+Math.max(1,Math.ceil(Array.from(line).reduce((w,c)=>w+(c.charCodeAt(0)>255?1:.6),0)*displayFont/(actorLabelWidth-24))),0);const actorLabelHeight=Math.max(160,actorLabelLines*displayFont*1.5+24);return <g key={n.id}><title>{n.text}</title>{!textOnly&&(actor?<g stroke="#506783" strokeWidth="2" fill="none"><circle cx={n.x+n.w/2} cy={n.y+15} r="13"/><path d={`M ${n.x+n.w/2} ${n.y+28} v 45 m -28 -30 h 56 m -28 30 l -23 25 m 23 -25 l 23 25`}/></g>:diamond?<polygon points={`${n.x+n.w/2},${n.y} ${n.x+n.w},${n.y+n.h/2} ${n.x+n.w/2},${n.y+n.h} ${n.x},${n.y+n.h/2}`} fill={fill} stroke={stroke} strokeWidth="1.6"/>:ellipse?<ellipse cx={n.x+n.w/2} cy={n.y+n.h/2} rx={n.w/2} ry={n.h/2} fill={fill} stroke={stroke} strokeWidth="1.6"/>:<rect x={n.x} y={n.y} width={n.w} height={n.h} rx={lane?0:st.rounded==='1'?8:2} fill={fill} stroke={stroke} strokeWidth="1.4" strokeDasharray={st.dashed==='1'?'7 5':undefined}/>)}{lane&&<line x1={n.x} y1={n.y+Number(st.startSize||50)} x2={n.x+n.w} y2={n.y+Number(st.startSize||50)} stroke="#c6d2e3"/>}{n.text&&<foreignObject x={actor?Math.max(12,Math.min(diagram.width-actorLabelWidth-12,n.x+n.w/2-actorLabelWidth/2)):n.x+(diamond?20:5)} y={n.y+(actor?110:0)} width={actor?actorLabelWidth:n.w-(diamond?40:10)} height={actor?actorLabelHeight:lane?Number(st.startSize||50):n.h}><div className={'graph-label '+(lane?'lane-label':'')+(textOnly?' graph-annotation':'')} style={{fontSize:displayFont,background:actor?'transparent':undefined,height:actor?'auto':undefined,fontWeight:st.fontStyle==='1'||lane?650:450,textAlign:st.align==='left'?'left':'center',justifyContent:actor||st.verticalAlign==='top'?'flex-start':'center'}}>{n.text.split('\n').filter(Boolean).map((line,i)=><div key={i}><Inline text={line}/></div>)}</div></foreignObject>}</g>}
 return <div className="diagram-shell"><div className="diagram-toolbar"><span><Network size={16}/> 图形视图</span><div className="zoom-buttons"><button onClick={()=>setZoom(z=>Math.max(.25,z-.15))} aria-label="缩小图形"><Minus size={16}/></button><output>{Math.round(zoom*100)}%</output><button onClick={()=>setZoom(z=>Math.min(1.8,z+.15))} aria-label="放大图形"><Plus size={16}/></button><button className="fit-button" onClick={fit}><Maximize2 size={15}/>适应宽度</button></div></div><div ref={wrap} className="diagram-viewport" tabIndex={0} aria-label="可滚动图形区域，使用上方按钮缩放"><svg width={diagram.width*zoom} height={diagram.height*zoom} viewBox={`0 0 ${diagram.width} ${diagram.height}`} aria-label={diagram.name}><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#8296b0"/></marker></defs>{backgrounds.map(shape)}{diagram.edges.map(e=>{const p=edgePath(e,map,straight);return p?<g key={e.id}><polyline points={p.points} fill="none" stroke="#8296b0" strokeWidth="1.7" strokeDasharray={e.style.dashed==='1'?'7 5':undefined} markerEnd={e.style.endArrow==='none'?undefined:`url(#${marker})`}/>{e.text&&<g transform={`translate(${p.label.x},${p.label.y})`}><rect x={-Math.max(28,e.text.length*7)} y="-14" width={Math.max(56,e.text.length*14)} height="28" rx="3" fill="#fff"/><text textAnchor="middle" dominantBaseline="middle" fill="#4b627e" fontSize="14">{e.text}</text></g>}</g>:null})}{foreground.filter(n=>!['umlActor','actor'].includes(n.style.shape)&&n.style.umlActor!=='1').map(shape)}{foreground.filter(n=>['umlActor','actor'].includes(n.style.shape)||n.style.umlActor==='1').map(shape)}</svg></div><div className="diagram-caption">保留全部节点与连线。可放大阅读，或切换到逐项阅读；蓝色 API 编号可跳转到接口详情。</div></div>
}
function DiagramTranscript({diagram}:{diagram:Diagram}){const parents=new Set(diagram.nodes.map(n=>n.parent));const nodes=diagram.nodes.filter(n=>n.text&&!parents.has(n.id)&&!n.id.startsWith('title')).sort((a,b)=>a.y-b.y||a.x-b.x);const map=new Map(diagram.nodes.map(n=>[n.id,n]));return <div className="transcript">{nodes.map((n,i)=>{const edges=diagram.edges.filter(e=>e.source===n.id&&map.has(e.target));return <article className="step-card" id={'node-'+diagram.id+'-'+n.id} key={n.id}><span className="step-index">{String(i+1).padStart(2,'0')}</span><div className="step-body">{n.lane&&<span className="lane-tag">{n.lane}</span>}<p className="preserve-lines"><Inline text={n.text}/></p>{edges.length>0&&<div className="next-steps">{edges.map(e=><a key={e.id} href={'#'+(data.components.includes(diagram)?'components':data.flows.includes(diagram)?'flows':data.usecases.includes(diagram)?'usecases':'modules')+'/'+diagram.id+'/'+e.target}><ArrowRight size={14}/>{e.text&&<b>{e.text}：</b>}{map.get(e.target)?.text.split('\n')[0]}</a>)}</div>}</div></article>})}</div>}
function DiagramCollection({kind,initial,node}:{kind:'components'|'modules'|'usecases'|'flows';initial?:string;node?:string}){const pages=data[kind];const [page,setPage]=useState(initial??pages[0].id);const [mode,setMode]=useState('graph');useEffect(()=>{if(initial&&pages.some(p=>p.id===initial))setPage(initial);if(node)setMode('reading')},[initial,node,pages]);const selected=pages.find(p=>p.id===page)??pages[0];useEffect(()=>{if(node&&mode==='reading'){const t=setTimeout(()=>document.getElementById('node-'+selected.id+'-'+node)?.scrollIntoView({block:'center',behavior:'smooth'}),80);return()=>clearTimeout(t)}},[node,mode,selected.id]);return <div className="diagram-collection"><Tabs value={page} onValueChange={v=>{setPage(String(v));setMode('graph')}}><TabsList className={'page-tabs '+(kind==='flows'?'flow-tabs':'')} variant="line">{pages.map(p=><TabsTrigger value={p.id} key={p.id}><span className="page-code">{p.id}</span>{p.name.replace(/^\d+\s*·\s*/,'')}</TabsTrigger>)}</TabsList>{pages.map(p=><TabsContent value={p.id} key={p.id}><div className="section-heading"><div><h2>{p.name.replace(/^\d+\s*·\s*/,'')}</h2>{kind==='flows'&&<p>{flowDescriptions[Number(p.id)]}</p>}</div><span className="node-count">{p.nodes.filter(n=>n.text&&!n.id.startsWith('lane')).length} 个内容节点</span></div><Tabs value={mode} onValueChange={v=>setMode(String(v))}><TabsList className="mode-tabs"><TabsTrigger value="graph"><Network size={16}/>图形视图</TabsTrigger><TabsTrigger value="reading"><BookOpen size={16}/>逐项阅读</TabsTrigger></TabsList><TabsContent value="graph"><DiagramCanvas diagram={p} straight={kind==='usecases'} readable={kind==='usecases'||kind==='components'}/></TabsContent><TabsContent value="reading"><DiagramTranscript diagram={p}/></TabsContent></Tabs></TabsContent>)}</Tabs></div>}
function ApiList({selected}:{selected?:string}){const [expanded,setExpanded]=useState<string[]>(selected?[selected]:[]);useEffect(()=>{if(selected){setExpanded([selected]);const t=setTimeout(()=>document.getElementById(selected)?.scrollIntoView({block:'start',behavior:'smooth'}),100);return()=>clearTimeout(t)}},[selected]);return <><div className="eyebrow">HTTP REFERENCE / 04</div><h1>对外 API 列表</h1><p className="intro">27 个 HTTP 接口，面向 APP 与云台。按模块浏览输入、输出、业务规则和对应流程。</p><div className="api-jumpbar">{data.moduleCards.map(m=><a href={'#api/'+m.apis[0]} key={m.id}><b>{m.id}</b>{m.name}<span>{m.apis.length}</span></a>)}</div><div className="api-design-note"><span className="blue-dot"/><span>接口设计稿 · 方法与路径已列出，字段和鉴权细节在正式对接时确定。</span></div>{data.moduleCards.map(mod=><section className="api-group" key={mod.id}><div className="api-group-title"><span className="module-code">{mod.id}</span><h2>{mod.name}</h2><span>{mod.apis.length} 个接口</span></div><Accordion multiple value={expanded} onValueChange={v=>setExpanded(v as string[])}>{data.apis.filter(a=>a.module===mod.id).map(api=><AccordionItem id={api.id} value={api.id} key={api.id} className="api-item"><AccordionTrigger className="api-trigger"><div className="api-trigger-main"><div className="api-title"><span className={'method method-'+api.method}>{api.method}</span><b>{api.title}</b><span className="api-id">{api.id}</span></div><code className="endpoint">{api.path}</code></div></AccordionTrigger><AccordionContent className="api-details"><div className="caller"><span>调用方</span><Inline text={api.caller}/></div><div className="contract-grid"><div><h3>输入要素</h3><p><Inline text={api.input}/></p></div><div><h3>输出要素</h3><p><Inline text={api.output}/></p></div></div><div className="contract-rules"><h3>业务规则</h3><p><Inline text={api.rules}/></p></div><div className="flow-links"><h3>对应流程</h3><div>{api.refs.split('；').map((ref,i)=>{const m=ref.match(/^(0[0-7])\/([a-z_0-9-]+)$/);return m?<a href={'#flows/'+m[1]+'/'+m[2]} key={ref}><GitBranch size={14}/>{ref}<ArrowUpRight size={13}/></a>:<span key={i}>{ref}</span>})}</div>{api.flowNote&&<p><Inline text={api.flowNote}/></p>}</div></AccordionContent></AccordionItem>)}</Accordion></section>)}<section className="conventions"><div className="section-heading"><div><h2>接口约定与业务说明</h2><p>范围、通用规则、逐页对应和客户端调用示例。</p></div></div><Accordion multiple>{data.sections.map((s,i)=><AccordionItem value={'section'+i} key={s.title}><AccordionTrigger>{s.title.replace(/^\d+\.\s*/,'')}</AccordionTrigger><AccordionContent><Markdown text={s.markdown}/></AccordionContent></AccordionItem>)}</Accordion></section></>}
function Workspace(){const [route,setRoute]=useState<{view:View;page?:string;node?:string}>({view:'modules'});useEffect(()=>{const sync=()=>{const [v,p,n]=location.hash.slice(1).split('/');if(v==='main-content')return;if(navigation.some(x=>x.id===v))setRoute({view:v as View,page:p,node:n});else setRoute({view:'modules'})};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);const nav=navigation.find(n=>n.id===route.view)!;const go=(v:View)=>{location.hash=v;window.scrollTo({top:0})};return <><a href="#main-content" className="skip-link">跳到正文</a><SideNavigation view={route.view} onNavigate={go}/><SidebarInset><header className="topbar"><SidebarTrigger aria-label="展开或收起导航"/><span className="breadcrumb">APP 与云台双控制<ChevronRight size={14}/><b>{nav.name}</b></span><span className="status"><span className="green-dot"/>当前设计</span></header><main className="workspace" id="main-content">{route.view==='detailed'||route.view==='face'||route.view==='technical'||route.view==='data'?<ArchitectureDocument kind={route.view} selected={route.page}/>:route.view==='tests'?<TestChecklist/>:route.view==='components'?<ComponentOverview/>:route.view==='modules'?<ModuleOverview/>:route.view==='api'?<ApiList selected={route.page}/>:<><div className="eyebrow">{route.view==='usecases'?'USE CASES / 02':'BUSINESS FLOWS / 03'}</div><h1>{route.view==='usecases'?'用例与参与角色':'从请求到完成的业务流程'}</h1><p className="intro">{route.view==='usecases'?'区分使用者、客户端与后端，查看每项能力对应的 HTTP API。':'沿用当前八页业务流程，保留判断分支、端侧动作和后端接口的边界。'}</p><DiagramCollection kind={route.view} initial={route.page} node={route.node}/></>}<footer className="page-footer"><span>LANSEE · 后端设计文档</span><span>5 个模块 / 27 个 HTTP API</span></footer></main></SidebarInset></>}
export default function Home(){return <SidebarProvider><Workspace/></SidebarProvider>}
