"""Export only the validated public build to the repository's generated web directory."""
from pathlib import Path
import shutil,tempfile
site=Path(__file__).resolve().parents[1]
source=site/'dist/client';target=site.parent/'web'
marker='.generated-by-lansee-docs'
assert (source/'index.html').is_file(), 'Missing static build'
if target.exists() and not (target/marker).is_file():
 raise SystemExit('Refusing to replace an unrecognized web directory')
stage=Path(tempfile.mkdtemp(prefix='.web-build-',dir=site.parent))
try:
 shutil.copytree(source,stage,dirs_exist_ok=True)
 (stage/marker).write_text('Generated by site/scripts/export-static.py; edit source documents and rebuild.\n')
 if target.exists(): shutil.rmtree(target)
 stage.rename(target)
finally:
 if stage.exists(): shutil.rmtree(stage)
print('Updated ../web from the static build.')
